version: '3'
services:
  hell_pot:
    build:
      context: DockerFile/hell_pot
      dockerfile: Dockerfile
    container_name: hell_pot
    restart: unless-stopped
    networks:
      main:
        ipv4_address: 172.20.1.1
    ports:
      - "8080:8080"

  endless_ssh:
    build:
      context: DockerFile/endlessh
      dockerfile: Dockerfile
    container_name: endless_ssh
    restart: unless-stopped
    networks:
      main:
        ipv4_address: 172.20.1.2
    ports:
      - "22:2222"

networks:
  main:
    external: true