version: '3'
services:
  hell_pot:
    build:
      context: DockerFile/hell_pot
      dockerfile: Dockerfile
    container_name: hell_pot
    restart: unless-stopped
    networks:
      main:
        ipv4_address: 172.20.1.1
    ports:
      - "8080:8080"

  endless_ssh:
    build:
      context: DockerFile/endlessh
      dockerfile: Dockerfile
    container_name: endless_ssh
    restart: unless-stopped
    networks:
      main:
        ipv4_address: 172.20.1.2
    ports:
      - "22:2222"

  ddospot:
    build:
        context: DockerFile/ddospot
        dockerfile: Dockerfile
    image: aelth/simpledns
    volumes:
        - ./honeypot/ddospot/bl:/ddospot/bl
        - ./honeypot/ddospot/db:/ddospot/db
        - ./honeypot/ddospot/logs:/ddospot/logs
        - ./honeypot/ddospot/pot:/ddospot/pot
    ports:
        - target: 19
          published: 19
          protocol: udp
          mode: host
        - target: 53
          published: 54
          protocol: udp
          mode: host
        - target: 123
          published: 123
          protocol: udp
          mode: host
        - target: 161
          published: 161
          protocol: udp
          mode: host
        - target: 1900
          published: 1901
          protocol: udp
          mode: host
    networks:
        main:
            ipv4_address: 172.20.1.3


networks:
  main:
    external: true