version: '3'

services:
  ohp:
    build:
      context: ./DockerFile/OWASP-honeypot
      dockerfile: Dockerfile.api
    command: bash -c "sleep 5 && python3 ohp.py --start-api-server"
    environment:
      - FLASK_ENV=development
      - ELASTICSEARCH_DOCKER_ENV=false
    ports:
      - "5000:5000"
    volumes:
      - ./honeypot/OWASP:/OWASP-Honey
    networks:
      main:
        ipv4_address: 172.20.0.7

  # cowrie:
  #  restart: always
  #  image: cowrie/cowrie
  #  ports:
  #    - "2222:2222"
  #    - "2223:2223"
  #  volumes:
  #    - ./honeypot/cowrie-etc:/cowrie/cowrie-git/etc
  #    - ./honeypot/cowrie-var:/cowrie/cowrie-git/var
  #  networks:
  #    main:
  #      ipv4_address: 172.20.0.8

networks:
  main:
    external: true