version: '3'
services:
  port_spoof:
    build:
      context: DockerFile/port_spoof
      dockerfile: Dockerfile
    container_name: port_spoof
    restart: unless-stopped
    networks:
      main:
        ipv4_address: 172.20.0.7
    expose:
      - 1-65535

networks:
  main:
    external: true
