name: Build & Publish ddospot Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::$
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Check for dockerenv file
        run: ls
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: docker/DockerFile/ddospot
          push: true
          platforms: linux/amd64,linux/arm64
          tags: valgul/ddospot:latest